CREATE DATABASE Cadastro;

USE Cadastro;

CREATE TABLE Usuarios (
Tag VARCHAR (20) PRIMARY  KEY,
Nome VARCHAR (80),
Documento VARCHAR (80)
);

CREATE TABLE Acessos (
num INTEGER PRIMARY KEY AUTO_INCREMENT,
Tag VARCHAR (20),
FOREIGN KEY (Tag) REFERENCES Usuarios(Tag),
RECORDED TIMESTAMP
);

CREATE TABLE Insercao (
Tag VARCHAR (20),
RECORDED TIMESTAMP
);